<?php
declare(strict_types=1);

// Benzokolonka SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

BenzokolonkaUtility::setRegistrar(function (BenzokolonkaUtility $u): void {
    $u->clean = [BenzokolonkaClean::class, 'call'];
    $u->done = [BenzokolonkaDone::class, 'call'];
    $u->make_error = [BenzokolonkaMakeError::class, 'call'];
    $u->feature_add = [BenzokolonkaFeatureAdd::class, 'call'];
    $u->feature_hook = [BenzokolonkaFeatureHook::class, 'call'];
    $u->feature_init = [BenzokolonkaFeatureInit::class, 'call'];
    $u->fetcher = [BenzokolonkaFetcher::class, 'call'];
    $u->make_fetch_def = [BenzokolonkaMakeFetchDef::class, 'call'];
    $u->make_context = [BenzokolonkaMakeContext::class, 'call'];
    $u->make_options = [BenzokolonkaMakeOptions::class, 'call'];
    $u->make_request = [BenzokolonkaMakeRequest::class, 'call'];
    $u->make_response = [BenzokolonkaMakeResponse::class, 'call'];
    $u->make_result = [BenzokolonkaMakeResult::class, 'call'];
    $u->make_point = [BenzokolonkaMakePoint::class, 'call'];
    $u->make_spec = [BenzokolonkaMakeSpec::class, 'call'];
    $u->make_url = [BenzokolonkaMakeUrl::class, 'call'];
    $u->param = [BenzokolonkaParam::class, 'call'];
    $u->prepare_auth = [BenzokolonkaPrepareAuth::class, 'call'];
    $u->prepare_body = [BenzokolonkaPrepareBody::class, 'call'];
    $u->prepare_headers = [BenzokolonkaPrepareHeaders::class, 'call'];
    $u->prepare_method = [BenzokolonkaPrepareMethod::class, 'call'];
    $u->prepare_params = [BenzokolonkaPrepareParams::class, 'call'];
    $u->prepare_path = [BenzokolonkaPreparePath::class, 'call'];
    $u->prepare_query = [BenzokolonkaPrepareQuery::class, 'call'];
    $u->graphql_body = [BenzokolonkaGraphql::class, 'body'];
    $u->graphql_errors = [BenzokolonkaGraphql::class, 'errors'];
    $u->result_basic = [BenzokolonkaResultBasic::class, 'call'];
    $u->result_body = [BenzokolonkaResultBody::class, 'call'];
    $u->result_headers = [BenzokolonkaResultHeaders::class, 'call'];
    $u->transform_request = [BenzokolonkaTransformRequest::class, 'call'];
    $u->transform_response = [BenzokolonkaTransformResponse::class, 'call'];
});
